use_frameworks!

target 'ReactiveSSE_Example' do
  pod 'ReactiveSSE', :path => '../'

  target 'ReactiveSSE_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
  pod 'Nimble', '~> 7.0.2'
  end
end
