platform :ios, '10.0'
use_frameworks!

target 'ReactiveSSE_Example' do
  pod 'ReactiveSSE', :path => '../'

  target 'ReactiveSSE_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
  end
end
